Repository ReproNim/reprostim, pull requests merged in 2025-01, with the labels that each got.

#127 Fix a typo by codespell
  src/reprostim/cli/cmd_detect_noscreen.py
Labels: patch, release

#131 Fixed hatch versioningit configuration
  pyproject.toml
  src/reprostim/__about__.py
Labels: bug, patch, release

#133 Provided additional documentation for reprostim CLI environment setup and hatch-based build
  .autorc
  README.md
Labels: documentation, patch, release

#134 Fixed 'SoundDeviceSound' object has no attribute 'duration' error
  src/reprostim/audio/audiocodes.py
Labels: bug, patch, release
