Repository ReproNim/reprostim, pull requests merged in 2025-05, with the labels that each got.

#149 Re-release and point SVG diagram link to RTD site, #125.
  README.md
Labels: bug, patch, release

#155 Fixes timesync-stimuly issues found during container setup on reproiner for automatic calibration
  src/reprostim/audio/audiocodes.py
  src/reprostim/qr/timesync_stimuli.py
Labels: bug, patch, release

#156 Streamline container recipes generation: do not bother with version in the recipe name, place in the folder of the script
  containers/repronim-reprostim/Dockerfile.repronim-reprostim
  containers/repronim-reprostim/Dockerfile.repronim-reprostim-0.7.9
  containers/repronim-reprostim/Singularity.repronim-reprostim
  containers/repronim-reprostim/Singularity.repronim-reprostim-0.7.5
  containers/repronim-reprostim/generate_container.sh
Labels: patch

#158 Setup CI/CD container workflow action
  .github/workflows/ci-cd.yml
  containers/repronim-reprostim/build_singularity.sh
  containers/repronim-reprostim/generate_container.sh
  containers/repronim-reprostim/run_reprostim_ci.sh
  tools/ci/build_reprostim_container.sh
  tools/ci/run_reprostim_container.sh
  tools/ci/test_reprostim_container.sh
Labels: enhancement, internal
